### PR TITLE
Add winstreak visualization

### PR DESCRIPTION
**Pull request by Olivia5k**
20231127 154833-dragonisle

---

## Winstreak visualization

As per the picture above, this adds a page that adds a neat overview of streaks in the Grandmastery challenge.  It adds a new page under the **Slay The Spire** heading in the main menu, and the page looks like in the above screenshot.  To preemptively answer the question _"Hey what run killed the streak?"_ the losing run is included in the grouping of the streak (but of course not counted in the streak total).

## Help needed!

While the UI is mostly complete, I am but a lowly frontend developer and do not possess the prowess to produce the data needed for this page to contain real data.  As of the making of this PR, the things shown in the screenshot above are hard-coded and as such are of little actual use.

I've added the class `StreakContainer` to help render this page.  The UI relies on it and its `@property` fields to render.  The work I need help with is to provide real data from the run caches and such, and y'all will be able to do that much faster and much better than I ever could.   I think I have left enough comments to make the work fairly clear.

Any questions and I'll help out, of course!

## Things left to do

- [x] Make the Python code do the thing. 

And some smaller things I can do meanwhile:
- [x] Make the blobs resize in a prettier way on wider screens
- [x] Something nicer to show the failed runs
- [ ] Mobile-adapted view 
- [x] Check accessibility (it's very color based, so it might be unusable for colorblind viewers)
- [x] Support streaks that are longer than 20 :eyes:

### CODE REVIEW

**Comment by Olivia5k** [comment]
@beeyee0401 Maybe you're the one that knows most about streaks and stuff?  Do we have the functionality needed already, or do you need to make something maybe?

**Comment by beeyee0401** [comment]
@Olivia5k This is ALL the runs during the challenge? Each RunParser object has Streak information and its position in a streak, if it exists. I suspect we have all the info we need. I think this could get a little dicey if we're showing Rotating on here too, since winning 10 IC runs in a row doesn't kill a rotating streak, and it does increment a rotating streak by 1 from the first IC win.

**Comment by Olivia5k** [comment]
@beeyee0401 Yeah, it is all runs grouped into streaks.  And yes, I know that the runs have the position that denotes which index they are in a streak.  What this needs is something that groups them together into `StreakContainer` objects. See [line 180](https://github.com/Spireblight/Spireblight/pull/86/files#diff-644d9ff05ced4216323f73e0c636aef3d5f53139dcd97c84541c9ad49da4ee97R180) in the PR!  I don't think we currently have anything that could group runs together like such, right?  (Also, I'm assuming we want to maybe cache this data so we don't re-calculate all of this anytime anyone goes to the streaks page.  Maybe that's a technical detail we don't need to discuss here.)

Regarding rotating streaks, we don't need to care for them right now - this is just for character streaks.  We can figure out something for the rotating streaks later, I'm sure :slightly_smiling_face:

**Comment by beeyee0401** [comment]
I see. runs.py does have them cached, so I think that should be fine. I'll work on this at some point and see what we can do. I still think we have everything we need.

**Comment by Olivia5k** [comment]
20231129 163435-dragonisle

---

My final suggestion for the page!  I have written the code that makes it happen too.  Please eviscerate it accordingly! :fire:

**Pull request merged**
