### PR TITLE
Update internal card handling to use the new, more complete version

### LINKED ISSUE #43: Task: Update the internal handling of cards, relics, etc. to use the new design
Right now, we're still using `get_card` and the like to get the card info. This is mostly fine, except that now we have a `full_data.json` file, which includes everything, as well as the Downfall stuff.

### PR DESCRIPTION
**Pull request by Vgr255**
Still a WIP. This will close #43. Remaining to do:

- [x] ~~Have `CardData` properly handle metadata as well as meta-scaling cards like Searing Blow~~ Edit: out of scope
- [x] Move `_get_cards` to the subclasses and make them use the full data
- [x] Make sure `_get_cards` and `_get_removals` are updated to the new internal API
- [x] Update the website handling for keys (I changed how they're returned to be better)
- [x] Add the card backs and description boxes for the colors of the new characters
- [x] Update API documentation
- [x] Bump minor version by 1

### CODE REVIEW

**Comment by Vgr255** [comment]
This is ready to be tested and reviewed. `CardData` doesn't know how to deal with meta-scaling cards (Ritual Dagger and Genetic Algorithm, and idk how Searing Blow is handled), though there's some baseline there. Can probably merge without this.

Make sure to update Docs while merging this. I can get on them this week.

**Review by Olivia5k — APPROVED** [review]
LGTM. 

Extremely minor:
The only thing I would personally change is that I don't like when functions are called overly generic things like `get` when there isn't necessarily context about them when they are called.  But, with good IDE tooling that matters slightly less I guess.

**Comment by brianyee** [comment]
I very much agree with Olivia here, I think our `get` function is getting too much. I'd like to separate it into `get_card` and things like that. Although it would create duplicates of the inner function because they would all be the same thing. Perhaps this is an issue with the design of how the json data is, we could put them each in its own key for `cards` or `relics`, etc. 

Or if we kept all the `get` functions looking the same, we could throw an exception if it's not the thing we're searching on. Throw an exception if you call `get_card` with a relic name or something

**Comment by Vgr255** [comment]
I empathize with the `nameinternal.get` function being a bit too generically-named. This is partly due to the fact that everything is in one file.

Something that I didn't communicate in this PR: I am planning for `full_data.json` to actually reside in another repository (not one that I control), and for the bot to pull from it on startup, as it can get updated regularly with changes to Downfall. As such, moving it into multiple files isn't feasible. I'm fine with having multiple functions, but as this is specifically for internal stuff, there *shouldn't* be conflicts.

Whatever we decide to do, this PR should not be merged until I (or someone else!) get around to writing API reference for this on the Docs repo.

**Pull request merged**
